### ISSUE TITLE
ModuleNotFoundError: No module named 'pydicom.dicomdir'

### ISSUE THREAD

**Issue by enrique-zarate** [dicomsort/dicomsorter#15]
Hi! I'm new to image processing 😄 

I have this issue while trying to run `dicomsorter --help`:
```
Traceback (most recent call last):
  File "/Users/my_user/dev/my_folder/bids_export/.venv/bin/dicomsorter", line 5, in <module>
    from dicomsorter.cli import main
  File "/Users/my_user/dev/my_folder/bids_export/.venv/lib/python3.12/site-packages/dicomsorter/cli.py", line 13, in <module>
    from .dicom_utils import available_fields
  File "/Users/my_user/dev/my_folder/bids_export/.venv/lib/python3.12/site-packages/dicomsorter/dicom_utils.py", line 7, in <module>
    from pydicom.dicomdir import DicomDir
ModuleNotFoundError: No module named 'pydicom.dicomdir'
```

More info:
OS: macOS Sonoma 14.5
Chip: M1

Pip freeze:
```
dicomsorter==0.1.0a6
dill==0.3.9
fasteners==0.19
multiprocess==0.70.16
pathos==0.3.2
pox==0.3.5
ppft==1.7.6.9
pydicom==3.0.1
tqdm==4.66.5
```

`python --version`:
```
Python 3.12.5
```

Steps:
```
python3 -python3 -m venv .venv 
source .venv/bin/activate  
pip install dicomsorter
dicomsorter --help
```

I hope it can help anyone else too!

**Comment by enrique-zarate** [comment]
I've noticed that I can correctly use the library if I use `dicomsort -h` through bidscoin (`pip install bidscoin`).

**Comment by chrstphmr** [comment]
I ran into the same issue. This error occurs because pydicom.dicomdir was replaced with a different API in pydicom 3.0 and setup.py currently does not force a pydicom version < 3.0.

You can circumvent this by running `pip install 'pydicom<3.0'` before installing dicomsorter (or bidscoin in your case).
